Adjust app navigation using expo-router  (#66)
* feat: install gluestack-ui components

* feat: configure glustack-ui v2

* feat: migrate components with codemode

* feat: set primary color

* fix: circular button

* fix: replace textLight by typography

* fix: add flat variant to Card

* fix: button group flex column

* fix: icon size on pin onboarding

* fix: ListTile typography color

* fix: AssetActionSheet icon space

* feat: adjust swap secreen

* feat: adjust operation buttons

* -fix: nativewind typescript support

* fix: simple modal body

* fix: ignore components/ui from lint

* fix: lint after codemode

* feat: delete deprecated gluestack-ui v1 theme

* fix: circular buttons bg and text size

* fix: delete missing gluestack v1 config

* chore: uninstall gluestack/themed and config

* fix: profile and scan font sizes

* fix: mocking toast

* fix: payment icons grid

* fix: feedback screen icon colors

* fix: sep24 transaction history

* feat: transfer screen

* fix: modals: icons, safe area, etc

* fix: profile lint

* fix: pin react-native-svg to fix RNSVGSvgView

* fix: android adjustments

* fix: unit tests

* chore: install dependencies with --legacy-peer-deps

* fix: toast test

* fix: lint

* fix: ReferenceError: You are trying to access a property or method of the Jest environment after it has been torn down. From

* fix: lint

* chore: add --legacy-peer-deps on expo updates

* chore: move legacy-peer-deps to .npmrc

* chore: update packages.lock

* fix: heap out of memory with max_old_space_size

* fix: Cannot find module 'ajv/dist/compile/codegen'

* fix: password recovery screen

* fix: disabling login button

* fix: workarround to disable buttons

* feat: increase wallet text

* fix: tests

* feat: increase logo size

* fix: adjust payment uttons alignment

* chore: improve navigation removing _layout files

* feat: adjust wallet navigation

* feat: adjust pin screen

* feat: scan from bottom

* feat: ux improvements

* feat: improve nav titles and back

* feat: improve all modals

* fix: test snapshorts

* fix: test